puts "Deleting existing ingredients..."
Ingredient.destroy_all

# 肉
ingredients = [
  { name: "鶏むね肉", price_per_gram: 0.85 },
  { name: "鶏もも肉", price_per_gram: 1.35 },
  { name: "鶏ささみ", price_per_gram: 1.10 },
  { name: "豚こま切れ肉", price_per_gram: 1.28 },
  { name: "豚バラ肉", price_per_gram: 1.98 },
  { name: "豚ロース肉", price_per_gram: 1.78 },
  { name: "合い挽き肉", price_per_gram: 1.18 },
  { name: "牛バラ肉", price_per_gram: 2.50 },
  { name: "牛もも肉(ブロック)", price_per_gram: 3.80 },
  { name: "牛すじ肉", price_per_gram: 1.60 },
  { name: "牛タン", price_per_gram: 6.50 },
  { name: "豚ヒレ肉", price_per_gram: 2.20 },
  { name: "豚肩ロース(ブロック)", price_per_gram: 1.85 },
  { name: "合鴨肉", price_per_gram: 3.50 },
  { name: "ラム肉", price_per_gram: 3.20 },
  { name: "ウインナー", price_per_gram: 1.50 },
  { name: "厚切りベーコン", price_per_gram: 1.90 },
  { name: "ハーフベーコン", price_per_gram: 2.10 },
  { name: "ロースハム", price_per_gram: 2.30 },
  { name: "生ハム", price_per_gram: 4.50 },
  { name: "サラミ", price_per_gram: 3.80 },

  # 野菜
  { name: "玉ねぎ", price_per_gram: 0.35 },
  { name: "にんじん", price_per_gram: 0.40 },
  { name: "じゃがいも", price_per_gram: 0.45 },
  { name: "キャベツ", price_per_gram: 0.20 },
  { name: "白菜", price_per_gram: 0.15 },
  { name: "大根", price_per_gram: 0.18 },
  { name: "もやし", price_per_gram: 0.15 },
  { name: "ブロッコリー", price_per_gram: 0.80 },
  { name: "ピーマン", price_per_gram: 0.65 },
  { name: "長ねぎ", price_per_gram: 0.55 },
  { name: "ほうれん草", price_per_gram: 0.75 },
  { name: "なす", price_per_gram: 0.65 },
  { name: "ズッキーニ", price_per_gram: 0.85 },
  { name: "トマト", price_per_gram: 0.70 },
  { name: "ミニトマト", price_per_gram: 1.10 },
  { name: "きゅうり", price_per_gram: 0.60 },
  { name: "アスパラガス", price_per_gram: 1.80 },
  { name: "オクラ", price_per_gram: 1.30 },
  { name: "小松菜", price_per_gram: 0.55 },
  { name: "ニラ", price_per_gram: 0.90 },
  { name: "レタス", price_per_gram: 0.45 },
  { name: "サニーレタス", price_per_gram: 0.65 },
  { name: "水菜", price_per_gram: 0.45 },
  { name: "チンゲン菜", price_per_gram: 0.60 },
  { name: "ゴーヤ", price_per_gram: 0.75 },
  { name: "かぼちゃ", price_per_gram: 0.35 },
  { name: "さつまいも", price_per_gram: 0.55 },
  { name: "里芋", price_per_gram: 0.65 },
  { name: "ごぼう", price_per_gram: 0.55 },
  { name: "れんこん", price_per_gram: 0.85 },
  { name: "たけのこ(水煮)", price_per_gram: 1.10 },
  { name: "ブロッコリースプラウト", price_per_gram: 1.90 },
  { name: "大葉(しそ)", price_per_gram: 8.50 },
  { name: "みょうが", price_per_gram: 3.20 },
  { name: "かいわれ大根", price_per_gram: 0.85 },
  { name: "パセリ", price_per_gram: 2.50 },
  { name: "にんにく", price_per_gram: 1.65 },
  { name: "生姜", price_per_gram: 1.20 },
  { name: "しいたけ", price_per_gram: 1.80 },
  { name: "しめじ", price_per_gram: 0.95 },
  { name: "えのき", price_per_gram: 0.45 },
  { name: "まいたけ", price_per_gram: 1.25 },
  { name: "エリンギ", price_per_gram: 0.90 },
  { name: "なめこ", price_per_gram: 0.85 },

  # 果物
  { name: "りんご", price_per_gram: 0.65 },
  { name: "バナナ", price_per_gram: 0.35 },
  { name: "みかん", price_per_gram: 0.55 },
  { name: "いちご", price_per_gram: 2.50 },
  { name: "ぶどう", price_per_gram: 1.80 },
  { name: "キウイ", price_per_gram: 1.20 },
  { name: "レモン", price_per_gram: 1.10 },
  { name: "アボカド", price_per_gram: 0.95 },

  # 魚
  { name: "鮭の切り身", price_per_gram: 2.50 },
  { name: "塩サバ", price_per_gram: 1.80 },
  { name: "真鯛(刺身用)", price_per_gram: 4.80 },
  { name: "マグロ(赤身)", price_per_gram: 5.50 },
  { name: "ブリ(切り身)", price_per_gram: 2.80 },
  { name: "アジ(開き)", price_per_gram: 1.40 },
  { name: "サンマ", price_per_gram: 1.80 },
  { name: "しらす干し", price_per_gram: 3.50 },
  { name: "むきえび", price_per_gram: 2.60 },
  { name: "冷凍あさり", price_per_gram: 1.20 },
  { name: "イカ", price_per_gram: 2.20 },
  { name: "タコ", price_per_gram: 4.20 },
  { name: "ホタテ(貝柱)", price_per_gram: 5.00 },
  { name: "カニカマ", price_per_gram: 0.95 },
  { name: "ちくわ", price_per_gram: 0.85 },
  { name: "さつま揚げ", price_per_gram: 1.10 },
  { name: "ツナ缶", price_per_gram: 2.10 },

  # 乳製品・豆腐など
  { name: "卵", price_per_gram: 0.45 },
  { name: "牛乳", price_per_gram: 0.25 },
  { name: "豆乳", price_per_gram: 0.28 },
  { name: "ヨーグルト", price_per_gram: 0.45 },
  { name: "バター", price_per_gram: 2.20 },
  { name: "マーガリン", price_per_gram: 0.95 },
  { name: "ピザ用チーズ", price_per_gram: 1.65 },
  { name: "粉チーズ", price_per_gram: 4.80 },
  { name: "スライスチーズ", price_per_gram: 2.10 },
  { name: "クリームチーズ", price_per_gram: 2.50 },
  { name: "納豆", price_per_gram: 0.70 },
  { name: "豆腐", price_per_gram: 0.25 },
  { name: "厚揚げ", price_per_gram: 0.65 },
  { name: "油揚げ", price_per_gram: 1.20 },
  { name: "こんにゃく", price_per_gram: 0.35 },
  { name: "しらたき", price_per_gram: 0.45 },
  { name: "ミックスビーンズ", price_per_gram: 1.35 },

  # 米
  { name: "白米(炊飯前)", price_per_gram: 0.70 },
  { name: "玄米", price_per_gram: 0.60 },
  { name: "無洗米", price_per_gram: 0.75 },
  { name: "もち米", price_per_gram: 0.85 },
  { name: "雑穀米(ミックス)", price_per_gram: 2.80 },
  { name: "押し麦", price_per_gram: 0.65 },
  { name: "オートミール", price_per_gram: 1.20 },
  { name: "切り餅", price_per_gram: 0.95 },
  { name: "赤飯", price_per_gram: 1.10 },

  # 麺類
  { name: "パスタ(乾麺)", price_per_gram: 0.30 },
  { name: "うどん(冷凍)", price_per_gram: 0.30 },
  { name: "そば(乾麺)", price_per_gram: 0.90 },
  { name: "そうめん(乾麺)", price_per_gram: 0.85 },
  { name: "中華麺(生)", price_per_gram: 0.65 },
  { name: "焼きそば麺", price_per_gram: 0.45 },
  { name: "ちゃんぽん麺", price_per_gram: 0.55 },
  { name: "フォー(米粉麺)", price_per_gram: 1.50 },
  { name: "春雨", price_per_gram: 1.10 },
  { name: "マロニー", price_per_gram: 1.20 },
  { name: "マカロニ", price_per_gram: 0.55 },
  { name: "ペンネ", price_per_gram: 0.60 },
  { name: "ラザニア板", price_per_gram: 1.80 },

  # パン
  { name: "食パン", price_per_gram: 0.50 },
  { name: "ベーグル", price_per_gram: 1.60 },
  { name: "クロワッサン", price_per_gram: 2.80 },
  { name: "ロールパン", price_per_gram: 0.90 },
  { name: "フランスパン", price_per_gram: 1.20 },
  { name: "ナン", price_per_gram: 1.50 },

  # 粉物
  { name: "強力粉", price_per_gram: 0.45 },
  { name: "中力粉(うどん粉)", price_per_gram: 0.40 },
  { name: "米粉", price_per_gram: 0.90 },
  { name: "お好み焼き粉", price_per_gram: 0.95 },
  { name: "たこ焼き粉", price_per_gram: 0.95 },
  { name: "ホットケーキミックス", price_per_gram: 0.85 },
  { name: "天ぷら粉", price_per_gram: 0.75 },
  { name: "から揚げ粉", price_per_gram: 2.20 },
  { name: "コーンスターチ", price_per_gram: 0.80 },
  { name: "餃子の皮", price_per_gram: 1.20 },
  { name: "春巻きの皮", price_per_gram: 1.40 },
  { name: "ワンタンの皮", price_per_gram: 1.30 },
  { name: "シュウマイの皮", price_per_gram: 1.30 },

  # シリアル
  { name: "コーンフレーク", price_per_gram: 1.10 },
  { name: "フルーツグラノーラ", price_per_gram: 1.20 },
  { name: "チョコワ", price_per_gram: 1.40 },

  # 調味料
  { name: "醤油", price_per_gram: 0.40 },
  { name: "味噌", price_per_gram: 0.60 },
  { name: "砂糖", price_per_gram: 0.25 },
  { name: "塩", price_per_gram: 0.15 },
  { name: "サラダ油", price_per_gram: 0.50 },
  { name: "料理酒", price_per_gram: 0.35 },
  { name: "みりん", price_per_gram: 0.45 },
  { name: "酢", price_per_gram: 0.30 },
  { name: "ポン酢", price_per_gram: 0.55 },
  { name: "めんつゆ(3倍濃縮)", price_per_gram: 0.65 },
  { name: "マヨネーズ", price_per_gram: 0.85 },
  { name: "ケチャップ", price_per_gram: 0.65 },
  { name: "オイスターソース", price_per_gram: 1.20 },
  { name: "豆板醤", price_per_gram: 1.50 },
  { name: "鶏ガラスープの素", price_per_gram: 2.80 },
  { name: "コンソメ(固形)", price_per_gram: 3.50 },
  { name: "和風だし顆粒", price_per_gram: 3.20 },
  { name: "カレールー", price_per_gram: 1.45 },
  { name: "カレー粉", price_per_gram: 1.20 },
  { name: "はちみつ", price_per_gram: 2.50 },
  { name: "片栗粉", price_per_gram: 0.65 },
  { name: "小麦粉(薄力粉)", price_per_gram: 0.35 },
  { name: "パン粉", price_per_gram: 0.85 },
  { name: "ごま油", price_per_gram: 1.45 },
  { name: "オリーブオイル", price_per_gram: 1.85 },
  { name: "白いりごま", price_per_gram: 1.50 },
  { name: "わさび(チューブ)", price_per_gram: 2.20 },
  { name: "からし(チューブ)", price_per_gram: 2.20 }
]

ingredients.each do |data|
  Ingredient.create!(data)
end

puts "Success: Created #{Ingredient.count} ingredients master data!"
