// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RecipeCalculationController from "./recipe_calculation_controller"
application.register("recipe-calculation", RecipeCalculationController)

import RecipePreviewController from "./recipe_preview_controller"
application.register("recipe-preview", RecipePreviewController)

import RecipeStepController from "./recipe_step_controller"
application.register("recipe-step", RecipeStepController)
